apiVersion: apps/v1
kind: Deployment
metadata: 
   name: nginx_deploying
spec:
 replicas: 1
 selector:
   matchLabels:
      app: nginx
 template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
      - name: nginxcontainer
        image: nginx.1.8
        ports:
          - containerPort: 80
