apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: collectionuat
type: Opaque
data:
  CLIENT_ID: 1001
  CLIENT_SECRET: 56FGnm82BfrCL6MKihQoL3NZe6YK

---
kubectl create secret tls <req secret name> --key <the.key file> --cert <cert or filke with 3keys> -n <req namespace>
